// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxkohfeelcvvortmjwxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4a29oZmVlbGN2dm9ydG1qd3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MzY1MjQsImV4cCI6MjA1OTIxMjUyNH0.X_vXQ0xpXAAJ00x7uy_7kgbIsD0fO5TlE69yLVAhy7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);